# Generated by Django 4.2.15 on 2024-09-03 07:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TerminalServer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.CharField(max_length=100, verbose_name='服务器IP/域名')),
                ('port', models.IntegerField(default=22, help_text='端口号', verbose_name='端口号')),
                ('remark', models.CharField(blank=True, max_length=100, null=True, verbose_name='备注')),
                ('username', models.CharField(max_length=200, verbose_name='用户名')),
                ('password', models.CharField(blank=True, max_length=200, null=True, verbose_name='密码')),
                ('pkey', models.CharField(blank=True, max_length=255, null=True, verbose_name='私钥')),
                ('pkey_passwd', models.CharField(blank=True, max_length=255, null=True, verbose_name='私钥密码')),
                ('type', models.SmallIntegerField(choices=[(0, '密码验证'), (1, '私钥验证')], default=0, help_text='验证方式', verbose_name='验证方式')),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '终端服务器列表',
                'verbose_name_plural': '终端服务器列表',
                'db_table': 'terminalserver',
            },
        ),
    ]
